apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  namespace: cartline-catalog
  labels:
    app.kubernetes.io/name: catalog-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: catalog-service
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
